'use client';

import React, { useState } from 'react';
import {
  BarChart3,
  Sparkles,
  Download,
  Calendar,
  FileText,
  TrendingUp,
  Brain,
  CheckCircle2,
  Plus
} from 'lucide-react';
import { CompanyReport, Employee, Project, Task } from '@/types';
import { createItem } from '@/lib/services/firestore';
import { callAI } from '@/lib/aiClient';

interface ReportViewProps {
  reports: CompanyReport[];
  employees: Employee[];
  projects: Project[];
  tasks: Task[];
  onRefresh: () => void;
}

export default function ReportView({
  reports,
  employees,
  projects,
  tasks,
  onRefresh
}: ReportViewProps) {
  const [reportType, setReportType] = useState<'Daily' | 'Monthly'>('Daily');
  const [generating, setGenerating] = useState(false);
  const [previewReport, setPreviewReport] = useState<string>('');

  const handleGenerateAICompanyReport = async () => {
    setGenerating(true);
    setPreviewReport('');
    try {
      const activeProjectsCount = projects.filter(p => p.status === 'In Progress').length;
      const tasksCompletedCount = tasks.filter(t => t.status === 'Completed').length;

      const aiText = await callAI('company-report', {
        type: reportType,
        state: {
          employeesCount: employees.length,
          activeProjects: activeProjectsCount,
          completedTasks: tasksCompletedCount,
          totalProjects: projects.length,
          totalTasks: tasks.length
        }
      });

      setPreviewReport(aiText);

      // Save to Firestore
      await createItem<Omit<CompanyReport, 'id'>>('reports', {
        title: `${reportType} Executive Operating Report - ${new Date().toLocaleDateString()}`,
        type: reportType,
        date: new Date().toISOString().split('T')[0],
        summary: aiText.substring(0, 300) + '...',
        metrics: {
          totalEmployees: employees.length,
          activeProjects: activeProjectsCount,
          tasksCompleted: tasksCompletedCount,
          overallProductivity: 92,
          revenueOrBudget: projects.reduce((acc, p) => acc + (p.budget || 0), 0)
        },
        keyHighlights: ['Automated AI synthesis generated by Gemini 2.5'],
        risksIdentified: ['Monitored via CEO Command'],
        aiRecommendations: ['Continue executing milestone sprints.'],
        createdBy: 'Gemini AI Assistant'
      });

      alert('Report Generated & Saved to Company Vault!');
    } catch (err: any) {
      alert('Error generating report: ' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-indigo-400" />
            Executive Reports & Company Audit Vault
          </h2>
          <p className="text-xs text-slate-400">Daily Operating Reports & Monthly Company Productivity Briefs</p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => { setReportType('Daily'); handleGenerateAICompanyReport(); }}
            disabled={generating}
            className="flex items-center gap-2 text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white px-3.5 py-2 rounded-xl transition-all shadow-md shadow-indigo-600/20"
          >
            <Sparkles className="w-4 h-4 text-indigo-200" />
            {generating && reportType === 'Daily' ? 'Generating...' : 'Generate Daily Report'}
          </button>
          <button
            onClick={() => { setReportType('Monthly'); handleGenerateAICompanyReport(); }}
            disabled={generating}
            className="flex items-center gap-2 text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white px-3.5 py-2 rounded-xl transition-all shadow-md shadow-emerald-600/20"
          >
            <Sparkles className="w-4 h-4 text-emerald-200" />
            {generating && reportType === 'Monthly' ? 'Generating...' : 'Generate Monthly Report'}
          </button>
        </div>
      </div>

      {/* Report Preview Container if newly generated */}
      {previewReport && (
        <div className="p-6 rounded-2xl bg-slate-900 border border-indigo-500/40 space-y-3 shadow-xl">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Brain className="w-4 h-4 text-indigo-400" />
              Newly Generated {reportType} Executive Operating Brief
            </h3>
            <button
              onClick={() => alert('Report saved in Firestore vault!')}
              className="text-xs font-semibold text-emerald-400 flex items-center gap-1"
            >
              <Download className="w-3.5 h-3.5" /> Export PDF/Markdown
            </button>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl text-slate-200 text-xs whitespace-pre-wrap leading-relaxed border border-slate-800">
            {previewReport}
          </div>
        </div>
      )}

      {/* Saved Reports History */}
      <div className="space-y-4">
        <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
          Saved Company Executive Reports ({reports.length})
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.map((r) => (
            <div
              key={r.id}
              className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-3 shadow-lg hover:border-indigo-500/50 transition-all"
            >
              <div className="flex items-start justify-between">
                <div>
                  <span className="text-[10px] font-mono text-indigo-400 uppercase tracking-wider block">
                    {r.type} Report • {r.date}
                  </span>
                  <h4 className="text-sm font-bold text-white mt-0.5">{r.title}</h4>
                </div>
                <span className="text-[10px] bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 px-2 py-0.5 rounded-full font-semibold">
                  By {r.createdBy}
                </span>
              </div>

              <div className="grid grid-cols-3 gap-2 bg-slate-950 p-2.5 rounded-xl border border-slate-800 text-[10px] text-center">
                <div>
                  <span className="text-slate-500 block">Workforce</span>
                  <span className="font-bold text-white">{r.metrics?.totalEmployees || employees.length}</span>
                </div>
                <div>
                  <span className="text-slate-500 block">Active Projects</span>
                  <span className="font-bold text-emerald-400">{r.metrics?.activeProjects || projects.length}</span>
                </div>
                <div>
                  <span className="text-slate-500 block">Tasks Completed</span>
                  <span className="font-bold text-purple-400">{r.metrics?.tasksCompleted || tasks.length}</span>
                </div>
              </div>

              <p className="text-xs text-slate-400 line-clamp-3 leading-relaxed">{r.summary}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
